### ISSUE TITLE
 Uncaught TypeError: Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by brandongalbraith** [freelawproject/recap-chrome#2]
When upload is attempted by Chrome RECAP extension from PACER, the following error occurs:

Uncaught TypeError: Cannot call method 'match' of undefined

at line 128 in recap.js

**Comment by audiodude** [comment]
I also see this error, looking into it now.

**Comment by audiodude** [comment]
It appears the server is giving back the following for my upload/ call:

Content-Type:text/html; charset=utf-8
upload: pdf ignored.

This is a string, not a JSON object, so the parsing of it fails and then the response is just a string not parsed data, so it has no "message" property, so the code:

```
cb(object && object.message.match(/pdf uploaded/i));
```

raises the exception in the bug title.

**Comment by mlissner** [comment]
Makes sense, and sounds like we can just catch the extension and ignore it, unless a fix on the server is possible.
