### ISSUE TITLE
Can't tell if files are being uploaded to RECAP

### ISSUE THREAD

**Issue by tjohns** [freelawproject/recap-chrome#4]
The RECAP feature list has this description of the automatic upload feature:

_"You will see a small notification box after each upload, which you can turn off if you wish."_

However, when I'm viewing PDF files on PACER, I don't see any notification that an upload is taking place.

**Comment by mlissner** [comment]
I think this is fixed! At least, I'm seeing lots of notifications now. Can you check with the latest version and and re-open this if you're still having issues?
