### ISSUE TITLE
500 Server error on load

### ISSUE THREAD

**Issue by audiodude** [freelawproject/recap-chrome#9]
When the extension loads, it requests `query/` with the following payload:

```
json=%7B%22court%22%3A%22azd%22%2C%22urls%22%3A%5B%22https%3A%2F%2Fecf.azd.uscourts.gov%2Fdoc1%2F02502773084%3F%22%5D%7D
```

This results in a 500 error:

```
Oops! This is a 500 error. How did this happen? Tell us what you did at bugs@recapthelaw.org. Thanks!
```

**Comment by mlissner** [comment]
That's a query to see if a specific document is in the collection. Is that happening when you just load the extension? There's something weird with Arizona, I think. Let me know if you need help server-side investigating this one.

**Comment by audiodude** [comment]
The decoded url is: `https://ecf.azd.uscourts.gov/doc1/02502773084?`

It is failing because of the trailing question mark.

I have filed https://github.com/freelawproject/recap-server/issues/53
